name: Build and Test
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:3.1.64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm i
      - name: Build project
        run: npm run build
      - name: List artifact files
        run: |
          ls -lh dist/wasm/internal/
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:3.1.64
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: npm-package
          path: .
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: npm run test
  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: npm-package
          path: .
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm pack
      - run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
